
DROP TABLE "MOIMUSER";
DROP TABLE "MOIMANS";
DROP TABLE "IMGBOARDANS";
DROP TABLE "IMGBOARD";
DROP TABLE "MOIM";
DROP TABLE "FREEBOARDANS";
DROP TABLE "FREEBOARD";
DROP TABLE "GROUPUSER";
DROP TABLE "GROUPINFO";
DROP TABLE "USERINFO";
DROP TABLE "SESSIONIDS";

DROP SEQUENCE "GROUPSEQ";
DROP SEQUENCE "BOARDSEQ";
DROP SEQUENCE "BOARDANSSEQ";
DROP SEQUENCE "MOIMSEQ";
DROP SEQUENCE "MOIMANSSEQ";
DROP SEQUENCE "IMGBOARDSEQ";
DROP SEQUENCE "IMGBOARDANSSEQ";

CREATE SEQUENCE "GROUPSEQ";
CREATE SEQUENCE "BOARDSEQ";
CREATE SEQUENCE "BOARDANSSEQ";
CREATE SEQUENCE "MOIMSEQ";
CREATE SEQUENCE "MOIMANSSEQ";
CREATE SEQUENCE "IMGBOARDSEQ";
CREATE SEQUENCE "IMGBOARDANSSEQ";

CREATE TABLE "USERINFO" (
	"USERID"	VARCHAR2(100)		NOT NULL,
	"USERPW"	VARCHAR2(100)		NOT NULL,
	"USERGRADE"	VARCHAR2(100)		NOT NULL,
	"USERNAME"	VARCHAR2(100)		NULL,
	"USERBIRTH"	VARCHAR2(100)		NOT NULL,
	"USEREMAIL"	VARCHAR2(1000)		NULL,
	"USERADDR"	VARCHAR2(1000)		NOT NULL,
	"USERGENDER"	VARCHAR2(100)		NOT NULL,
	"USERPHONE"	VARCHAR2(100)		NOT NULL,
	"USERREGDATE"	DATE		NOT NULL
);
INSERT INTO USERINFO VALUES('0','0','Manager','愿�由ъ옄','1996-08-24','1@GAMIL.COM','媛뺣궓','W','01034785503',SYSDATE);
INSERT INTO USERINFO VALUES('1','1','user','�씠由�1','1996-08-24','1@GAMIL.COM','媛뺣궓','W','01034785503',SYSDATE);
INSERT INTO USERINFO VALUES('2','2','user','�씠由�2','1996-08-24','1@GAMIL.COM','媛뺣궓','W','01034785503',SYSDATE);
INSERT INTO USERINFO VALUES('3','3','user','�씠由�3','1996-08-24','1@GAMIL.COM','媛뺣궓','W','01034785503',SYSDATE);
INSERT INTO USERINFO VALUES('bbqq0108','123123123','user','�씠由�3','1996-08-24','1@GAMIL.COM','媛뺣궓','W','01034785503',SYSDATE);
--SELECT * FROM USERINFO;

CREATE TABLE "GROUPINFO" (
	"GROUPNO"	NUMBER		NOT NULL,
	"GROUPTITLE"	VARCHAR2(100)		NULL,
	"GROUPCONTENT"	VARCHAR2(1000)		NOT NULL,
	"GROUPREGDATE"	DATE		NOT NULL,
	"GROUPIMG"	VARCHAR2(1000)		NULL
);

INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎1','�궡�슜�엯�땲�떎1',SYSDATE,'/s/img/sample_img1.jpg');
INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎2','�궡�슜�엯�땲�떎2',SYSDATE,'/s/img/sample_img2.jpg');
INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎3','�궡�슜�엯�땲�떎3',SYSDATE,'/s/img/sample_img3.jpg');
INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎4','�궡�슜�엯�땲�떎4',SYSDATE,'/s/img/sample_img4.jpg');
INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎5','�궡�슜�엯�땲�떎5',SYSDATE,'/s/img/sample_img5.jpg');
INSERT INTO GROUPINFO VALUES(GROUPSEQ.NEXTVAL,'�젣紐⑹엯�땲�떎6','�궡�슜�엯�땲�떎6',SYSDATE,'/s/img/sample_img6.jpg');

--SELECT * FROM GROUPINFO;
--SELECT * FROM GROUPUSER;

--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='1';
--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='2';
--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='3';
--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='4';
--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='5';
--UPDATE GROUPUSER SET GROUPUSERGRADE='MASTER' WHERE USERID='0' AND GROUPNO='6';

CREATE TABLE "GROUPUSER" (
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"GROUPUSERGRADE"	VARCHAR2(100)		NOT NULL,
	"GROUPUSERREGDATE"	DATE		NOT NULL
);

CREATE TABLE "FREEBOARD" (
	"BOARDNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"BOARDTITLE"	VARCHAR2(100)		NOT NULL,
	"BOARDCONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARDREGDATE"	DATE		NOT NULL
);
INSERT INTO FREEBOARD VALUES(BOARDSEQ.NEXTVAL, '0', 6, '�옄�쑀寃뚯떆�뙋�젣紐�1', '�옄�쑀寃뚯떆�뙋�궡�슜1', SYSDATE);
INSERT INTO FREEBOARD VALUES(BOARDSEQ.NEXTVAL, '0', 6, '�옄�쑀寃뚯떆�뙋�젣紐�2', '�옄�쑀寃뚯떆�뙋�궡�슜2', SYSDATE);

CREATE TABLE "MOIMUSER" (
	"MOIMNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"MOIMQ1"	NUMBER		NULL,
	"MOIMQ2"	NUMBER		NULL,
	"MOIMQ3"	NUMBER		NULL,
	"MOIMQ4"	NUMBER		NULL,
	"MOIMQ5"	NUMBER		NULL,
	"MOIMQ6"	VARCHAR2(100)		NULL
);

CREATE TABLE "FREEBOARDANS" (
	"BOARDANSNO"	NUMBER		NOT NULL,
	"BOARDNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"BOARDANSCONTENT"	VARCHAR2(1000)		NOT NULL,
	"BOARDANSREGDATE"	DATE		NOT NULL
);

CREATE TABLE "IMGBOARD" (
	"IMGBOARDNO"	NUMBER		NOT NULL,
	"MOIMNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"IMGBOARDTITLE"	VARCHAR2(100)		NULL,
	"IMGBOARDCONTENT"	VARCHAR2(4000)		NULL,
	"IMGBOARDREGDATE"	DATE		NULL,
	"IMGBOARDIMG"	VARCHAR2(1000)		NULL
);

INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�1','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img1.jpg');
INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�2','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img2.jpg');
INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�3','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img3.jpg');
INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�4','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img4.jpg');
INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�5','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img5.jpg');
INSERT INTO IMGBOARD VALUES(IMGBOARDSEQ.NEXTVAL,6,'0',6,'媛ㅻ윭由ъ젣紐�6','媛ㅻ윭由щ궡�슜',SYSDATE,'/s/img/sample_img6.jpg');

CREATE TABLE "IMGBOARDANS" (
	"IMGANSNO"	NUMBER		NOT NULL,
	"IMGBOARDNO"	NUMBER		NOT NULL,
	"MOIMNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"IMGANSCONTENT"	VARCHAR2(1000)		NOT NULL,
	"IMGANSREGDATE"	DATE		NOT NULL
);

CREATE TABLE "MOIMANS" (
	"MOIMANSNO"	NUMBER		NOT NULL,
	"MOIMNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"MOIMANSCONTENT"	VARCHAR2(1000)		NOT NULL,
	"MOIMANSREGDATE"	DATE		NOT NULL
);

CREATE TABLE "MOIM" (
	"MOIMNO"	NUMBER		NOT NULL,
	"USERID"	VARCHAR2(100)		NOT NULL,
	"GROUPNO"	NUMBER		NOT NULL,
	"MOIMTITLE"	VARCHAR2(100)		NOT NULL,
	"MOIMCONTENT"	VARCHAR2(4000)		NOT NULL,
	"MOIMRECRUIT"	VARCHAR2(100)		NOT NULL,
	"MOIMADDR"	VARCHAR2(1000)		NOT NULL,
	"LAT"	VARCHAR2(100)		NULL,
	"LNG"	VARCHAR2(100)		NULL,
	"MOIMREGDATE"	DATE		NOT NULL,
	"MOIMENDDATE"	VARCHAR2(100)		NOT NULL,
	"MOIMDATE"	VARCHAR2(100)		NULL
);

CREATE TABLE "SESSIONIDS" (
	"SESSIONID"	VARCHAR2(100)		NULL,
	"USERID"	VARCHAR2(100)		NULL,
	"GROUPNO"	NUMBER	NOT NULL
);

SELECT * FROM MOIMUSER;


ALTER TABLE "USERINFO" ADD CONSTRAINT "PK_USERINFO" PRIMARY KEY (
	"USERID"
);

ALTER TABLE "GROUPINFO" ADD CONSTRAINT "PK_GROUPINFO" PRIMARY KEY (
	"GROUPNO"
);

ALTER TABLE "GROUPUSER" ADD CONSTRAINT "PK_GROUPUSER" PRIMARY KEY (
	"USERID",
	"GROUPNO"
);

ALTER TABLE "FREEBOARD" ADD CONSTRAINT "PK_FREEBOARD" PRIMARY KEY (
	"BOARDNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "MOIMUSER" ADD CONSTRAINT "PK_MOIMUSER" PRIMARY KEY (
	"MOIMNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "FREEBOARDANS" ADD CONSTRAINT "PK_FREEBOARDANS" PRIMARY KEY (
	"BOARDANSNO",
	"BOARDNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "IMGBOARD" ADD CONSTRAINT "PK_IMGBOARD" PRIMARY KEY (
	"IMGBOARDNO",
	"MOIMNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "IMGBOARDANS" ADD CONSTRAINT "PK_IMGBOARDANS" PRIMARY KEY (
	"IMGANSNO",
	"IMGBOARDNO",
	"MOIMNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "MOIMANS" ADD CONSTRAINT "PK_MOIMANS" PRIMARY KEY (
	"MOIMANSNO",
	"MOIMNO",
	"USERID",
	"GROUPNO"
);

ALTER TABLE "MOIM" ADD CONSTRAINT "PK_MOIM" PRIMARY KEY (
	"MOIMNO",
	"USERID",
	"GROUPNO"
);








